#pragma once
#include "engine/textureManager.h"

TextureID CITY_TEXTURE_ID;
TextureID FACTORY_TEXTURE_ID;
TextureID MINE_TEXTURE_ID;
TextureID BUILDING_OUTLINE_TEXTURE_ID;
TextureID BUILDING_SHADOW_TEXTURE_ID;
TextureID CAPITAL_TEXTURE_ID;
TextureID WALL_TEXTURE_ID;
TextureID WALL_SHADOW_TEXTURE_ID;

TextureID INFANTRY_TEXTURE_ID;
TextureID CAVALRY_TEXTURE_ID;
TextureID ARTILLERY_TEXTURE_ID;
TextureID GROUND_OUTLINE_TEXTURE_ID;
TextureID GROUND_SHADOW_TEXTURE_ID;

TextureID BULLET_TEXTURE_ID;
TextureID SHELL_TEXTURE_ID;
TextureID COIN_TEXTURE_ID;
TextureID ORE_TEXTURE_ID;

void Textures_Init();